#!/bin/bash

# terminate already running polybar
killall -q polybar

# wait until the processes have been shutdown
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# launch bar1 and bar 2
# polybar example &
polybar example -r &
